/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
  package parser;

  import util.*;
  import java.util.Stack;
  import java.util.Iterator;

  /** A class for performing syntactic analysis
   * */
  public class Parser implements ParserConstants {
      /** Maximum string size allowed */
      public static final int MAX_STRING_SIZE = 5000;
      /** Is debugging enabled? */
      private static boolean debug = false;
      /** Filenames of source files */
      private static String[] filenames = null;
      /** Input streams of source files */
      private static java.io.FileInputStream[] fileReaders = null;
      /** Current file number (index into filenames and fileReaders) */
      private static int fileCnt = 0;

      public Parser(String[] filenames, boolean debug) {
          // set debugging flag
          this.debug = debug;

          // initialize filenames field to parameter filenames
          // used later for finding the name of the current file
          this.filenames = filenames;

          // check that there is at least one specified filename
          if (filenames.length == 0)
              throw new RuntimeException(
                     "Must specify at least one filename to scan");
          // must initialize readers for each file (FileInputStream)
          fileReaders = new java.io.FileInputStream[filenames.length];
          for (int i = 0; i < filenames.length; i++) {
              // try...catch checks if file is found
              try {
                  // create the ith file reader
                  fileReaders[i] = new java.io.FileInputStream(filenames[i]);
              }
              catch(java.io.FileNotFoundException e) {
                  // if file not found then report an error and exit
                  System.err.println("Error: file '" +
                                     filenames[i] + "' not found");
                  System.exit(1);
              }
          }

          if (jj_initialized_once) {
              System.out.println(
              "ERROR: Second call to constructor of static parser.  You must" +
              "       either use ReInit() or set the JavaCC option STATIC to " +
              "false       during parser generation.");
              throw new Error();
          }
          jj_initialized_once = true;

          try { jj_input_stream =
                      new JavaCharStream(fileReaders[0], null, 1, 1); }
          catch(java.io.UnsupportedEncodingException e) {
              throw new RuntimeException(e);
          }

          ReInit(fileReaders[0]);
      }

      /** Parse program
        * @return parsed program as an AST (abstract syntax tree)
        * */
      public boolean parse() {
          // initialize the error handler and class list
          ErrorHandler errorHandler = new ErrorHandler();

          // loop over the files
          for (fileCnt = 0; fileCnt < fileReaders.length; fileCnt++) {
              try {
                  if (fileCnt > 0)
                           jj_input_stream.ReInit(fileReaders[fileCnt], 1, 1);

                  Parser.Program();

                  System.out.println( filenames[fileCnt] +
                                      " is syntactically correct.");

              }
              catch(ParseException e) {

                  String message = e.toString();
                  int index = message.indexOf(": ");
                  message = message.substring(index+2,message.length());
                  errorHandler.register(
                          errorHandler.PARSE_ERROR, filenames[fileCnt],
                          JavaCharStream.getBeginLine(), message);
              }
          }
          errorHandler.checkErrors();

          return true;
      }

      /** Get the filename of the file currently being scanned
        * */
      public static String getCurrFilename() {
          return filenames[fileCnt];
      }

/******************************************/
/* Add your grammar rules below ...       */
/******************************************/

/* 

Precedence (from highest to lowest)
10  new  ()
9   . (dispatch) [] ++ -- (postfix)[left]
8   - (unary) !     ++ -- (prefix) [right]
7   (casting)                      [right]
6   * / %                          [left]
5   + -                            [left]
4   < <= > >= instanceof           [left]
3   == !=                          [left]
2   &&                             [left]
1   ||                             [left]
0   =                              [right]

*/


/* Precedence has yet to be handled */
  static final public void Program() throws ParseException {
    Class();
    jj_consume_token(0);
  }

  static final public void Class() throws ParseException {
    jj_consume_token(CLASS);
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EXTENDS:{
      jj_consume_token(EXTENDS);
      jj_consume_token(ID);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(LBRACKET);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      Member();
    }
    jj_consume_token(RBRACKET);
  }

  static final public void Member() throws ParseException {
    Formal();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      Method();
      break;
      }
    case ASSIGN:
    case SEMICOLON:{
      Field();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void Method() throws ParseException {
    jj_consume_token(LPAREN);
    Formal();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      Formal();
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACKET);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WHILE:
      case IF:
      case FOR:
      case NEW:
      case RETURN:
      case LPAREN:
      case LBRACKET:
      case INCREMENT:
      case SUB:
      case DECREMENT:
      case NOT:
      case PERIOD:
      case BREAK:
      case INT_CONST:
      case BOOLEAN_CONST:
      case STRING_CONST:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      Stmt();
    }
    jj_consume_token(RBRACKET);
  }

  static final public void Field() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      Expr();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
  }

  static final public void Formal() throws ParseException {
    jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      jj_consume_token(LBRACE);
      jj_consume_token(RBRACE);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(ID);
  }

  static final public void Stmt() throws ParseException {
    if (jj_2_1(3)) {
      ExprStmt();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        DeclStmt();
        break;
        }
      case IF:{
        IfStmt();
        break;
        }
      case WHILE:{
        WhileStmt();
        break;
        }
      case FOR:{
        ForStmt();
        break;
        }
      case BREAK:{
        BreakStmt();
        break;
        }
      case RETURN:{
        ReturnStmt();
        break;
        }
      case LBRACKET:{
        BlockStmt();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void ExprStmt() throws ParseException {
    Expr();
  }

  static final public void DeclStmt() throws ParseException {
    Formal();
    jj_consume_token(ASSIGN);
    Expr();
    jj_consume_token(SEMICOLON);
  }

  static final public void IfStmt() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    Expr();
    jj_consume_token(RPAREN);
    Stmt();
    optionalelse();
  }

//(<ELSE>Stmt())?
  static final public 
void optionalelse() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      Stmt();
      break;
      }
    default:
      jj_la1[8] = jj_gen;

    }
  }

  static final public void WhileStmt() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    Expr();
    jj_consume_token(RPAREN);
    Stmt();
  }

  static final public void ForStmt() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INCREMENT:
    case SUB:
    case DECREMENT:
    case NOT:
    case PERIOD:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:
    case ID:{
      Expr();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INCREMENT:
    case SUB:
    case DECREMENT:
    case NOT:
    case PERIOD:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:
    case ID:{
      Expr();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INCREMENT:
    case SUB:
    case DECREMENT:
    case NOT:
    case PERIOD:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:
    case ID:{
      Expr();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    Stmt();
  }

  static final public void BreakStmt() throws ParseException {
    jj_consume_token(BREAK);
    jj_consume_token(SEMICOLON);
  }

  static final public void ReturnStmt() throws ParseException {
    jj_consume_token(RETURN);
    if (jj_2_2(2)) {
      Expr();
    } else {
      ;
    }
  }

  static final public void BlockStmt() throws ParseException {
    jj_consume_token(LBRACKET);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case WHILE:
      case IF:
      case FOR:
      case NEW:
      case RETURN:
      case LPAREN:
      case LBRACKET:
      case INCREMENT:
      case SUB:
      case DECREMENT:
      case NOT:
      case PERIOD:
      case BREAK:
      case INT_CONST:
      case BOOLEAN_CONST:
      case STRING_CONST:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
      Stmt();
    }
    jj_consume_token(RBRACKET);
  }

  static final public void Expr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case PERIOD:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:
    case ID:{
      AssignExpr();
      break;
      }{
      DispatchExpr();
      break;
      }{
      NewExpr();
      break;
      }{
      InstanceofExpr();
      break;
      }{
      CastExpr();
      break;
      }{
      BinaryExpr();
      break;
      }
    case INCREMENT:
    case SUB:
    case DECREMENT:
    case NOT:{
      UnaryExpr();
      break;
      }{
      ConstExpr();
      break;
      }{
      VarExpr();
      break;
      }{
      jj_consume_token(LPAREN);
      Expr();
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void AssignExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:
    case ID:{
      VarExpr();
      jj_consume_token(ASSIGN);
      Expr();
      break;
      }
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      BasicExp();
      VarExpr();
      jj_consume_token(ASSIGN);
      Expr();
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void VarExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:{
      VarExpr1();
      break;
      }
    case ID:{
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACE:{
        jj_consume_token(LBRACE);
        Expr();
        jj_consume_token(RBRACE);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void VarExpr1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:{
      jj_consume_token(PERIOD);
      Expr();
      break;
      }{
      jj_consume_token(PERIOD);
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACE:{
        jj_consume_token(LBRACE);
        Expr();
        jj_consume_token(RBRACE);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void DispatchExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      BasicExp();
      DispatchExpr1();
      break;
      }
    case ID:{
      jj_consume_token(ID);
      jj_consume_token(LPAREN);
      Expr();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        Expr();
      }
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void DispatchExpr1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:{
      jj_consume_token(PERIOD);
      Expr();
      break;
      }{
      jj_consume_token(PERIOD);
      jj_consume_token(ID);
      jj_consume_token(LPAREN);
      Expr();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        Expr();
      }
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void NewExpr() throws ParseException {
    jj_consume_token(NEW);
    jj_consume_token(ID);
    NewExpr1();
  }

  static final public void NewExpr1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      break;
      }
    case LBRACE:{
      jj_consume_token(LBRACE);
      Expr();
      jj_consume_token(RBRACE);
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void InstanceofExpr() throws ParseException {
    BasicExp();
    jj_consume_token(INSTANCEOF);
    InstanceofExpr1();
  }

  static final public void InstanceofExpr1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACE:{
        jj_consume_token(LBRACE);
        jj_consume_token(RBRACE);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        ;
      }
      Expr();
      break;
      }{
      jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACE:{
        jj_consume_token(LBRACE);
        jj_consume_token(RBRACE);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void CastExpr() throws ParseException {
    jj_consume_token(LPAREN);
    jj_consume_token(ID);
    if (jj_2_3(2)) {

    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    CastExpr1();
  }

  static final public void CastExpr1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      jj_consume_token(LBRACE);
      jj_consume_token(RBRACE);
      jj_consume_token(RPAREN);
      jj_consume_token(LPAREN);
      Expr();
      jj_consume_token(RPAREN);
      break;
      }
    case RPAREN:{
      jj_consume_token(RPAREN);
      jj_consume_token(LPAREN);
      Expr();
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      BinaryArithExpr();
      break;
      }{
      BinaryCompExpr();
      break;
      }{
      BinaryLogicExpr();
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void UnaryExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case DECREMENT:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      UnaryDecrExpr();
      break;
      }
    case INCREMENT:{
      UnaryIncrExpr();
      break;
      }
    case SUB:{
      UnaryNegExpr();
      break;
      }
    case NOT:{
      UnaryNotExpr();
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ConstExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT_CONST:{
      jj_consume_token(INT_CONST);
      break;
      }
    case BOOLEAN_CONST:{
      jj_consume_token(BOOLEAN_CONST);
      break;
      }
    case STRING_CONST:{
      jj_consume_token(STRING_CONST);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryArithExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      label_7:
      while (true) {
        BasicExp();
        jj_consume_token(PLUS);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[31] = jj_gen;
          break label_7;
        }
      }
      Expr();
      break;
      }{
      label_8:
      while (true) {
        BasicExp();
        jj_consume_token(SUB);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[32] = jj_gen;
          break label_8;
        }
      }
      Expr();
      break;
      }{
      BinaryArithExpr2();
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//Expr()BAE1()Expr()
  static final public void BinaryArithExpr2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      label_9:
      while (true) {
        BasicExp();
        jj_consume_token(TIMES);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[34] = jj_gen;
          break label_9;
        }
      }
      Expr();
      break;
      }{
      label_10:
      while (true) {
        BasicExp();
        jj_consume_token(DIV);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[35] = jj_gen;
          break label_10;
        }
      }
      Expr();
      break;
      }{
      label_11:
      while (true) {
        BasicExp();
        jj_consume_token(MOD);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[36] = jj_gen;
          break label_11;
        }
      }
      Expr();
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryCompExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      label_12:
      while (true) {
        BasicExp();
        jj_consume_token(EQUAL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[38] = jj_gen;
          break label_12;
        }
      }
      Expr();
      break;
      }{
      label_13:
      while (true) {
        BasicExp();
        jj_consume_token(NOT_EQUAL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          break label_13;
        }
      }
      Expr();
      break;
      }{
      BinaryCompExpr2();
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryCompExpr2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      label_14:
      while (true) {
        BasicExp();
        jj_consume_token(LT);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          break label_14;
        }
      }
      Expr();
      break;
      }{
      label_15:
      while (true) {
        BasicExp();
        jj_consume_token(LTE);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[42] = jj_gen;
          break label_15;
        }
      }
      Expr();
      break;
      }{
      label_16:
      while (true) {
        BasicExp();
        jj_consume_token(GT);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          break label_16;
        }
      }
      Expr();
      break;
      }{
      label_17:
      while (true) {
        BasicExp();
        jj_consume_token(GTE);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[44] = jj_gen;
          break label_17;
        }
      }
      Expr();
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryLogicExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      label_18:
      while (true) {
        BasicExp();
        jj_consume_token(AND);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:
        case LPAREN:
        case INT_CONST:
        case BOOLEAN_CONST:
        case STRING_CONST:{
          ;
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          break label_18;
        }
      }
      Expr();
      break;
      }{
      BinaryLogicExpr2();
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BinaryLogicExpr2() throws ParseException {
    label_19:
    while (true) {
      BasicExp();
      jj_consume_token(OR);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NEW:
      case LPAREN:
      case INT_CONST:
      case BOOLEAN_CONST:
      case STRING_CONST:{
        ;
        break;
        }
      default:
        jj_la1[48] = jj_gen;
        break label_19;
      }
    }
    Expr();
  }

  static final public void BasicExp() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      ConstExpr();
      break;
      }
    case LPAREN:{
      CastExpr();
      break;
      }
    case NEW:{
      NewExpr();
      break;
      }
    default:
      jj_la1[49] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void UnaryNegExpr() throws ParseException {
    jj_consume_token(SUB);
    Expr();
  }

  static final public void UnaryNotExpr() throws ParseException {
    jj_consume_token(NOT);
    Expr();
  }

  static final public void UnaryIncrExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INCREMENT:{
      jj_consume_token(INCREMENT);
      Expr();
      break;
      }
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT_CONST:
      case BOOLEAN_CONST:
      case STRING_CONST:{
        ConstExpr();
        break;
        }
      case LPAREN:{
        CastExpr();
        break;
        }
      case NEW:{
        NewExpr();
        break;
        }
      default:
        jj_la1[50] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(INCREMENT);
      break;
      }
    default:
      jj_la1[51] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void UnaryDecrExpr() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DECREMENT:{
      jj_consume_token(DECREMENT);
      Expr();
      break;
      }
    case NEW:
    case LPAREN:
    case INT_CONST:
    case BOOLEAN_CONST:
    case STRING_CONST:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT_CONST:
      case BOOLEAN_CONST:
      case STRING_CONST:{
        ConstExpr();
        break;
        }
      case LPAREN:{
        CastExpr();
        break;
        }
      case NEW:{
        NewExpr();
        break;
        }
      default:
        jj_la1[52] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DECREMENT);
      break;
      }
    default:
      jj_la1[53] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_3R_20()
 {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_104()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_107()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_103()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_106()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_102()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_105()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_89()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_102()) {
    jj_scanpos = xsp;
    if (jj_3R_103()) {
    jj_scanpos = xsp;
    if (jj_3R_104()) return true;
    }
    }
    if (jj_scan_token(DECREMENT)) return true;
    return false;
  }

  static private boolean jj_3R_91()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_105()) {
    jj_scanpos = xsp;
    if (jj_3R_106()) {
    jj_scanpos = xsp;
    if (jj_3R_107()) return true;
    }
    }
    if (jj_scan_token(INCREMENT)) return true;
    return false;
  }

  static private boolean jj_3R_88()
 {
    if (jj_scan_token(DECREMENT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_66()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_88()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) return true;
    }
    return false;
  }

  static private boolean jj_3R_90()
 {
    if (jj_scan_token(INCREMENT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_67()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) return true;
    }
    return false;
  }

  static private boolean jj_3R_62()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_69()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_61()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_68()
 {
    if (jj_scan_token(SUB)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_116()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(OR)) return true;
    return false;
  }

  static private boolean jj_3R_101()
 {
    Token xsp;
    if (jj_3R_116()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_116()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_87()
 {
    if (jj_3R_101()) return true;
    return false;
  }

  static private boolean jj_3R_100()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(AND)) return true;
    return false;
  }

  static private boolean jj_3R_86()
 {
    Token xsp;
    if (jj_3R_100()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_100()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_65()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_86()) {
    jj_scanpos = xsp;
    if (jj_3R_87()) return true;
    }
    return false;
  }

  static private boolean jj_3R_123()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(GTE)) return true;
    return false;
  }

  static private boolean jj_3R_122()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(GT)) return true;
    return false;
  }

  static private boolean jj_3R_115()
 {
    Token xsp;
    if (jj_3R_123()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_123()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_60()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_121()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(LTE)) return true;
    return false;
  }

  static private boolean jj_3R_120()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(LT)) return true;
    return false;
  }

  static private boolean jj_3R_114()
 {
    Token xsp;
    if (jj_3R_122()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_122()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_113()
 {
    Token xsp;
    if (jj_3R_121()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_121()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_112()
 {
    Token xsp;
    if (jj_3R_120()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_120()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_99()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_112()) {
    jj_scanpos = xsp;
    if (jj_3R_113()) {
    jj_scanpos = xsp;
    if (jj_3R_114()) {
    jj_scanpos = xsp;
    if (jj_3R_115()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_98()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(NOT_EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_85()
 {
    if (jj_3R_99()) return true;
    return false;
  }

  static private boolean jj_3R_97()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(EQUAL)) return true;
    return false;
  }

  static private boolean jj_3R_84()
 {
    Token xsp;
    if (jj_3R_98()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_98()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_64()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_83()
 {
    Token xsp;
    if (jj_3R_97()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_97()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_119()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(MOD)) return true;
    return false;
  }

  static private boolean jj_3R_118()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(DIV)) return true;
    return false;
  }

  static private boolean jj_3R_111()
 {
    Token xsp;
    if (jj_3R_119()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_119()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_110()
 {
    Token xsp;
    if (jj_3R_118()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_118()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_117()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(TIMES)) return true;
    return false;
  }

  static private boolean jj_3R_82()
 {
    if (jj_3R_96()) return true;
    return false;
  }

  static private boolean jj_3R_109()
 {
    Token xsp;
    if (jj_3R_117()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_117()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_96()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_109()) {
    jj_scanpos = xsp;
    if (jj_3R_110()) {
    jj_scanpos = xsp;
    if (jj_3R_111()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_95()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(SUB)) return true;
    return false;
  }

  static private boolean jj_3R_81()
 {
    Token xsp;
    if (jj_3R_95()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_95()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_94()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3R_63()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_80()
 {
    Token xsp;
    if (jj_3R_94()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_44()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_52()
 {
    if (jj_3R_69()) return true;
    return false;
  }

  static private boolean jj_3R_57()
 {
    return false;
  }

  static private boolean jj_3R_51()
 {
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_50()
 {
    if (jj_3R_67()) return true;
    return false;
  }

  static private boolean jj_3R_49()
 {
    if (jj_3R_66()) return true;
    return false;
  }

  static private boolean jj_3R_48()
 {
    if (jj_3R_65()) return true;
    return false;
  }

  static private boolean jj_3R_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_47()
 {
    if (jj_3R_64()) return true;
    return false;
  }

  static private boolean jj_3R_46()
 {
    if (jj_3R_63()) return true;
    return false;
  }

  static private boolean jj_3R_42()
 {
    if (jj_3R_45()) return true;
    if (jj_3R_40()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_37()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_75()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_56()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    }
    return false;
  }

  static private boolean jj_3R_74()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_77()
 {
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_58()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) return true;
    }
    return false;
  }

  static private boolean jj_3R_76()
 {
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_35()
 {
    if (jj_3R_45()) return true;
    if (jj_scan_token(INSTANCEOF)) return true;
    if (jj_3R_56()) return true;
    return false;
  }

  static private boolean jj_3R_36()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_57()) return true;
    if (jj_3R_58()) return true;
    return false;
  }

  static private boolean jj_3R_108()
 {
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_71()
 {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_73()
 {
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    return false;
  }

  static private boolean jj_3R_72()
 {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_59()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) return true;
    }
    return false;
  }

  static private boolean jj_3R_78()
 {
    if (jj_scan_token(PERIOD)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_79()
 {
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_54()
 {
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_43()
 {
    if (jj_3R_45()) return true;
    if (jj_3R_59()) return true;
    return false;
  }

  static private boolean jj_3R_34()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_3R_55()) return true;
    return false;
  }

  static private boolean jj_3R_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    return false;
  }

  static private boolean jj_3R_93()
 {
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_108()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_92()
 {
    if (jj_scan_token(PERIOD)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_70()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) return true;
    }
    return false;
  }

  static private boolean jj_3R_41()
 {
    if (jj_3R_40()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_32()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  static private boolean jj_3R_40()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    return false;
  }

  static private boolean jj_3R_53()
 {
    if (jj_3R_70()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_31()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_30()
 {
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_29()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_28()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_27()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_26()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_25()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_24()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_23()
 {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_22()
 {
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3R_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(0)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static JavaCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[54];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4,0x0,0x82000,0x0,0x20e0a1d8,0x80000,0x20000,0x8158,0x20,0x20e02080,0x20e02080,0x20e02080,0x20e0a1d8,0x20e02080,0x2080,0x20000,0x0,0x20000,0x0,0x0,0x2080,0x0,0x0,0x22000,0x20000,0x20000,0x0,0x24000,0x2080,0x20e02080,0x0,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x2080,0x202080,0x2080,0x802080,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x1000,0x1,0x4,0x1e42,0x0,0x0,0x1040,0x0,0x1e02,0x1e02,0x1e02,0x1e42,0x1e02,0x1e02,0x0,0x1002,0x0,0x2,0x4,0x1e00,0x4,0x2,0x0,0x0,0x0,0x1000,0x0,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,0xe00,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[3];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 54; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[48];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 54; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 48; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
